/**
 * Selfbits API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DevicePushEndpoint {
    id?: string;

    pushServiceType?: DevicePushEndpoint.PushServiceTypeEnum;

    userId?: string;

    deviceId?: string;

    uuid?: string;

    registrationId?: string;

    isEnabled?: boolean;

    isValid?: boolean;

    customData?: any;

}
export namespace DevicePushEndpoint {
    export enum PushServiceTypeEnum {
        FCM = <any> 'FCM',
        APN = <any> 'APN'
    }
}

