/**
 * Selfbits API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface NewPushService {
    id?: string;

    name: string;

    description?: string;

    pushServiceType: NewPushService.PushServiceTypeEnum;

    fcmSenderId?: string;

    fcmApiKey?: string;

    apnCertificate?: string;

    apnPrivateKey?: string;

    apnProviderTokenP8Key?: string;

    apnProviderTokenKeyId?: string;

    apnProviderTokenTeamId?: string;

    apnIsDevelopment?: boolean;

    apnAppBundleId?: string;

    defaultTransmissionOptions?: any;

    customData?: any;

}
export namespace NewPushService {
    export enum PushServiceTypeEnum {
        FCM = <any> 'FCM',
        APN = <any> 'APN'
    }
}

