/**
 * Selfbits API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface NewTopic {
    id?: string;

    name: string;

    description?: string;

    enabled?: boolean;

    notificationType?: NewTopic.NotificationTypeEnum;

    isSubscriptionRestricted?: boolean;

    subscriptionRole?: string;

    notificationTemplateId?: string;

    customData?: any;

}
export namespace NewTopic {
    export enum NotificationTypeEnum {
        EMAIL = <any> 'EMAIL',
        PUSH = <any> 'PUSH',
        SMS = <any> 'SMS',
        WEBHOOK = <any> 'WEBHOOK'
    }
}

