/**
 * Selfbits API V2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RestEndpoint {
    id?: string;

    resource?: string;

    resourcePath?: string;

    method?: RestEndpoint.MethodEnum;

    description?: string;

    stage?: string;

    version?: number;

    actionId?: string;

    config?: any;

    customData?: any;

}
export namespace RestEndpoint {
    export enum MethodEnum {
        GET = <any> 'GET',
        POST = <any> 'POST',
        PUT = <any> 'PUT',
        DELETE = <any> 'DELETE'
    }
}

