export * from './AuthApi';
import { AuthApi } from './AuthApi';
export * from './FilesApi';
import { FilesApi } from './FilesApi';
export * from './InteractiveViewsApi';
import { InteractiveViewsApi } from './InteractiveViewsApi';
export * from './JoinApi';
import { JoinApi } from './JoinApi';
export * from './MongodbApi';
import { MongodbApi } from './MongodbApi';
export * from './OrganizationsApi';
import { OrganizationsApi } from './OrganizationsApi';
export * from './RestApi';
import { RestApi } from './RestApi';
export * from './TenantsApi';
import { TenantsApi } from './TenantsApi';
export * from './UsersApi';
import { UsersApi } from './UsersApi';
export const APIS_APP = [AuthApi, FilesApi, InteractiveViewsApi, JoinApi, MongodbApi, OrganizationsApi, RestApi, TenantsApi, UsersApi];
