export * from './ActionsApi';
import { ActionsApi } from './ActionsApi';
export * from './ApplicationsApi';
import { ApplicationsApi } from './ApplicationsApi';
export * from './ClientsApi';
import { ClientsApi } from './ClientsApi';
export * from './ConsumersApi';
import { ConsumersApi } from './ConsumersApi';
export * from './DirectoriesApi';
import { DirectoriesApi } from './DirectoriesApi';
export * from './EmailVerificationApi';
import { EmailVerificationApi } from './EmailVerificationApi';
export * from './EndpointsApi';
import { EndpointsApi } from './EndpointsApi';
export * from './FilemetasApi';
import { FilemetasApi } from './FilemetasApi';
export * from './InteractiveAuthenticationApi';
import { InteractiveAuthenticationApi } from './InteractiveAuthenticationApi';
export * from './InteractiveLoginApi';
import { InteractiveLoginApi } from './InteractiveLoginApi';
export * from './InteractiveSignupApi';
import { InteractiveSignupApi } from './InteractiveSignupApi';
export * from './InvitesApi';
import { InvitesApi } from './InvitesApi';
export * from './LoginApi';
import { LoginApi } from './LoginApi';
export * from './MongoDataApi';
import { MongoDataApi } from './MongoDataApi';
export * from './MongoDatabasesApi';
import { MongoDatabasesApi } from './MongoDatabasesApi';
export * from './MongoModelsApi';
import { MongoModelsApi } from './MongoModelsApi';
export * from './OrganizationsApi';
import { OrganizationsApi } from './OrganizationsApi';
export * from './ProvidersApi';
import { ProvidersApi } from './ProvidersApi';
export * from './RolesApi';
import { RolesApi } from './RolesApi';
export * from './SignupApi';
import { SignupApi } from './SignupApi';
export * from './TenantsApi';
import { TenantsApi } from './TenantsApi';
export * from './UsersApi';
import { UsersApi } from './UsersApi';
export const APIS = [ActionsApi, ApplicationsApi, ClientsApi, ConsumersApi, DirectoriesApi, EmailVerificationApi, EndpointsApi, FilemetasApi, InteractiveAuthenticationApi, InteractiveLoginApi, InteractiveSignupApi, InvitesApi, LoginApi, MongoDataApi, MongoDatabasesApi, MongoModelsApi, OrganizationsApi, ProvidersApi, RolesApi, SignupApi, TenantsApi, UsersApi];
